/** @format */

const aeroportos = [
  {
    Sigla: "SBTK",
    Aeroporto: "Tarauacá",
    Estado: "AC",
    Latitude: -8.1617,
    Longitude: -70.7654,
  },
  {
    Sigla: "SBRB",
    Aeroporto: "Presidente Médici",
    Estado: "AC",
    Latitude: -9.8696,
    Longitude: -67.8967,
  },
  {
    Sigla: "SBCZ",
    Aeroporto: "Internacional",
    Estado: "AC",
    Latitude: -9.5108,
    Longitude: -35.7911,
  },
  {
    Sigla: "SBMO",
    Aeroporto: "Zumbi dos Palmares",
    Estado: "AL",
    Latitude: -9.5108,
    Longitude: -35.7911,
  },
  {
    Sigla: "SBEG",
    Aeroporto: "Eduardo Gomes",
    Estado: "AM",
    Latitude: -3.0386,
    Longitude: -60.0497,
  },
  {
    Sigla: "SBMN",
    Aeroporto: "Ponta Pelada",
    Estado: "AM",
    Latitude: -3.0503,
    Longitude: -60.0469,
  },
  {
    Sigla: "SBMY",
    Aeroporto: "Manicoré",
    Estado: "AM",
    Latitude: -5.8092,
    Longitude: -61.2775,
  },
  {
    Sigla: "SBTT",
    Aeroporto: "Tabatinga",
    Estado: "AM",
    Latitude: -4.2425,
    Longitude: -69.9324,
  },
  {
    Sigla: "SBYA",
    Aeroporto: "Iuaretê",
    Estado: "AM",
    Latitude: -0.3486,
    Longitude: -65.4117,
  },
  {
    Sigla: "SBUA",
    Aeroporto: "São Gabriel da Cachoeira",
    Estado: "AM",
    Latitude: -0.1186,
    Longitude: -67.0847,
  },
  {
    Sigla: "SBTF",
    Aeroporto: "Tefé",
    Estado: "AM",
    Latitude: -3.3825,
    Longitude: -64.7192,
  },
  {
    Sigla: "SBAM",
    Aeroporto: "Amapá",
    Estado: "AP",
    Latitude: 2.0792,
    Longitude: -50.8539,
  },
  {
    Sigla: "SBMQ",
    Aeroporto: "Internacional",
    Estado: "AP",
    Latitude: 0.0503,
    Longitude: -51.0725,
  },
  {
    Sigla: "SBOI",
    Aeroporto: "Oiapoque",
    Estado: "AP",
    Latitude: 3.8614,
    Longitude: -51.8208,
  },
  {
    Sigla: "SBLP",
    Aeroporto: "Bom Jesus da Lapa",
    Estado: "BA",
    Latitude: -13.2631,
    Longitude: -43.4036,
  },
  {
    Sigla: "SBCV",
    Aeroporto: "Caravelas",
    Estado: "BA",
    Latitude: -17.7267,
    Longitude: -39.2539,
  },
  {
    Sigla: "SBIL",
    Aeroporto: "Jorge Amado",
    Estado: "BA",
    Latitude: -14.8158,
    Longitude: -39.0322,
  },
  {
    Sigla: "SBLE",
    Aeroporto: "Chapada Diamantina",
    Estado: "BA",
    Latitude: -12.4761,
    Longitude: -41.2811,
  },
  {
    Sigla: "SBUF",
    Aeroporto: "Paulo Afonso",
    Estado: "BA",
    Latitude: -9.3964,
    Longitude: -38.2464,
  },
  {
    Sigla: "SBPS",
    Aeroporto: "Porto Seguro",
    Estado: "BA",
    Latitude: -16.4386,
    Longitude: -39.0806,
  },
  {
    Sigla: "SBSV",
    Aeroporto: "Dep. Luís Eduardo Magalhães",
    Estado: "BA",
    Latitude: -12.9119,
    Longitude: -38.3319,
  },
  {
    Sigla: "SBQV",
    Aeroporto: "Vitória da Conquista",
    Estado: "BA",
    Latitude: -14.8625,
    Longitude: -40.8625,
  },
  {
    Sigla: "SBFZ",
    Aeroporto: "Pinto Martins",
    Estado: "CE",
    Latitude: -3.7761,
    Longitude: -38.5322,
  },
  {
    Sigla: "SBJU",
    Aeroporto: "Cariri",
    Estado: "CE",
    Latitude: -7.2122,
    Longitude: -39.2725,
  },
  {
    Sigla: "SBBR",
    Aeroporto: "Juscelino Kubitschek",
    Estado: "DF",
    Latitude: -15.8614,
    Longitude: -47.9122,
  },
  {
    Sigla: "SBVT",
    Aeroporto: "Eurico Aguiar Salles",
    Estado: "ES",
    Latitude: -20.2553,
    Longitude: -40.2764,
  },
  {
    Sigla: "SBAN",
    Aeroporto: "Anápolis",
    Estado: "GO",
    Latitude: -16.2322,
    Longitude: -48.9536,
  },
  {
    Sigla: "SBGO",
    Aeroporto: "Santa Genoveva",
    Estado: "GO",
    Latitude: -16.6319,
    Longitude: -49.2219,
  },
  {
    Sigla: "SBCI",
    Aeroporto: "Carolina",
    Estado: "MA",
    Latitude: -7.3383,
    Longitude: -47.4636,
  },
  {
    Sigla: "SBIZ",
    Aeroporto: "Imperatriz",
    Estado: "MA",
    Latitude: -5.5306,
    Longitude: -47.4728,
  },
  {
    Sigla: "SBSL",
    Aeroporto: "Mar. Cunha Machado",
    Estado: "MA",
    Latitude: -2.5867,
    Longitude: -44.2347,
  },
  {
    Sigla: "SBAX",
    Aeroporto: "Araxá",
    Estado: "MG",
    Latitude: -19.5603,
    Longitude: -46.9606,
  },
  {
    Sigla: "SBPR",
    Aeroporto: "Carlos Prates",
    Estado: "MG",
    Latitude: -19.8703,
    Longitude: -43.9686,
  },
  {
    Sigla: "SBBQ",
    Aeroporto: "Barbacena",
    Estado: "MG",
    Latitude: -21.2622,
    Longitude: -43.7611,
  },
  {
    Sigla: "SBBH",
    Aeroporto: "Pampulha",
    Estado: "MG",
    Latitude: -19.8506,
    Longitude: -43.9506,
  },
  {
    Sigla: "SBCF",
    Aeroporto: "Tancredo Neves",
    Estado: "MG",
    Latitude: -19.6336,
    Longitude: -43.9689,
  },
  {
    Sigla: "SBPC",
    Aeroporto: "Poços de Caldas",
    Estado: "MG",
    Latitude: -21.8444,
    Longitude: -46.5692,
  },
  {
    Sigla: "SBUR",
    Aeroporto: "Uberaba",
    Estado: "MG",
    Latitude: -19.7414,
    Longitude: -47.9642,
  },
  {
    Sigla: "SBUL",
    Aeroporto: "Uberlândia",
    Estado: "MG",
    Latitude: -18.8819,
    Longitude: -48.2261,
  },
  {
    Sigla: "SBIP",
    Aeroporto: "Ipatinga",
    Estado: "MG",
    Latitude: -19.4706,
    Longitude: -42.4875,
  },
  {
    Sigla: "SBJF",
    Aeroporto: "Francisco de Assis",
    Estado: "MG",
    Latitude: -21.7917,
    Longitude: -43.3883,
  },
  {
    Sigla: "SBMK",
    Aeroporto: "Montes Claros",
    Estado: "MG",
    Latitude: -16.7072,
    Longitude: -43.8192,
  },
  {
    Sigla: "SBVG",
    Aeroporto: "Varginha",
    Estado: "MG",
    Latitude: -21.5889,
    Longitude: -45.4728,
  },
  {
    Sigla: "SBGV",
    Aeroporto: "Gov. Valadares",
    Estado: "MG",
    Latitude: -18.8956,
    Longitude: -41.9828,
  },
  {
    Sigla: "SBCG",
    Aeroporto: "Internacional",
    Estado: "MS",
    Latitude: -20.4697,
    Longitude: -54.6725,
  },
  {
    Sigla: "SBCR",
    Aeroporto: "Corumbá",
    Estado: "MS",
    Latitude: -19.0119,
    Longitude: -57.6661,
  },
  {
    Sigla: "SBPP",
    Aeroporto: "Internacional",
    Estado: "MS",
    Latitude: -22.5497,
    Longitude: -55.7044,
  },
  {
    Sigla: "SBAT",
    Aeroporto: "Alta Floresta",
    Estado: "MT",
    Latitude: -9.8664,
    Longitude: -56.0861,
  },
  {
    Sigla: "SBBW",
    Aeroporto: "Barra do Garças",
    Estado: "MT",
    Latitude: -15.8611,
    Longitude: -52.3825,
  },
  {
    Sigla: "SBCY",
    Aeroporto: "Marechal Rondon",
    Estado: "MT",
    Latitude: -15.6533,
    Longitude: -56.1161,
  },
];

const orderBy = (aeroportos) => {
  return aeroportos.sort((a, b) => {
    const nomeA = a.Aeroporto.toUpperCase();
    const nomeB = b.Aeroporto.toUpperCase();

    if (nomeA < nomeB) {
      return -1;
    }
    if (nomeA > nomeB) {
      return 1;
    }
    return 0;
  });
};

export const orderByName = orderBy(aeroportos);
